-- drop all the objects before dropping roles
DROP database IF EXISTS @DB_CSPACE_NAME@;

DROP USER IF EXISTS @DB_CSPACE_USER@;

CREATE ROLE @DB_CSPACE_USER@ WITH PASSWORD '@DB_CSPACE_PASSWORD@' LOGIN;

--
-- recreate cspace database
--
CREATE DATABASE @DB_CSPACE_NAME@ ENCODING 'UTF8' OWNER @DB_CSPACE_USER@;
