CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(128) NOT NULL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  passwd VARCHAR(128) NOT NULL,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tokens (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  account_csid VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  expire_seconds INTEGER NOT NULL,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);
