 /*	
 * IDPart
 *
 * <p>Models a part of an identifier (ID).</p>
 *
 * <p>Some representative examples of data that can be
 * managed within IDParts include:</p>
 *
 * <ul>
 *   <li>Incrementing numeric or alphabetic values</li>
 *   <li>Date values</li>
 *   <li>Static separators</li>
 * </ul>
 *
 * This document is a part of the source code and related artifacts
 * for CollectionSpace, an open source collections management system
 * for museums and related institutions:
 *
 * http://www.collectionspace.org
 * http://wiki.collectionspace.org
 *
 * Copyright © 2009 Regents of the University of California
 *
 * Licensed under the Educational Community License (ECL), Version 2.0.
 * You may not use this file except in compliance with this License.
 *
 * You may obtain a copy of the ECL 2.0 License at
 * https://source.collectionspace.org/collection-space/LICENSE.txt
 *
 * $LastChangedBy$
 * $LastChangedRevision$
 * $LastChangedDate$
 */

// @TODO: Add Javadoc comments

package org.collectionspace.services.id;

public abstract class IDPart {

	// A generator for the types of IDs that are generated by this part.
	// This generator is passed in at construction time.
	protected IDGenerator generator;
	
	// Constructor
	public IDPart(IDGenerator idGenerator) throws IllegalArgumentException {
		this.generator = idGenerator;
	}

	// Returns the initial value of the ID associated with this IDPart.
	public String getInitialID() {
		return generator.getInitialID();
	}

	// Returns the current value of the ID associated with this IDPart.
	public String getCurrentID() {
		return generator.getCurrentID();
	}

	// Sets the current value of the ID associated with this IDPart.
	public void setCurrentID(String value) throws IllegalArgumentException {
		generator.setCurrentID(value);
	}

	// Resets the ID associated with this IDPart to its initial value.
	public void resetID() {
		generator.resetID();
	}

	// Returns the next ID in the sequence, and sets the current value
	// of the ID associated with this IDPart to that next ID.
	public String nextID() throws IllegalStateException {
		return generator.nextID();
	}

	// Validates a supplied ID against the pattern of this IDPart.
	//
	// Some IDParts may offer generic validation,
	// while others may offer per-instance valiadation
	// based on the values, series, etc. that are
	// stored within those parts.
	public boolean isValidID(String value) throws IllegalArgumentException {
		return generator.isValidID(value);
	}

	// Returns a String representation of the regular expression ("regex")
	// pattern used to validate instance values of this IDPart.  
	public String getRegex() {
		return generator.getRegex();
	}
 
}
